import {
   imgCarousel_1,
   imgCarousel_2,
   imgCarousel_3,
   imgCarousel_4,
   imgCarousel_5,
   imgCarousel_6,
   catTelevisores,
   catCelulares,
   catClimatizacion,
   catColchonesSommiers,
   catLavarropasLavavajillas,
   catNotebook,
   catHeladeras,
   catHerrElectricas,
   catAguaCaliente,
   catCocinas,
   catPequenosElec,
   catCuidadoPersonal,
   tv1,
   cel1,
   heladera1,
   bordeadora1,
   batidora1,
   lavavajillas1,
   notebook1,
   cama1,
   sillon1,
   cocina1,
} from './images';

import { nanoid } from 'nanoid';

const slideImages = [
   imgCarousel_1,
   imgCarousel_2,
   imgCarousel_3,
   imgCarousel_4,
   imgCarousel_5,
   imgCarousel_6,
];

const categoriesData = [
   {
      nombre: 'Televisores',
      img: catTelevisores,
   },
   {
      nombre: 'Celulares',
      img: catCelulares,
   },
   {
      nombre: 'Climatizacion',
      img: catClimatizacion,
   },
   {
      nombre: 'Colchones y Sommiers',
      img: catColchonesSommiers,
   },
   {
      nombre: 'Lavarropas y Lavavajillas',
      img: catLavarropasLavavajillas,
   },
   {
      nombre: 'Notebooks',
      img: catNotebook,
   },
   {
      nombre: 'Heladeras, Freezers y Cavas',
      img: catHeladeras,
   },
   {
      nombre: 'Herramientas Eléctricas',
      img: catHerrElectricas,
   },
   {
      nombre: 'Agua Caliente',
      img: catAguaCaliente,
   },
   {
      nombre: 'Cocinas y Hornos',
      img: catCocinas,
   },
   {
      nombre: 'Pequeños Electrodomésticos',
      img: catPequenosElec,
   },
   {
      nombre: 'Cuidado Personal',
      img: catCuidadoPersonal,
   },
];

const products = [
   {
      id: nanoid(5),
      titulo: 'Smart TV 50" 4K UHD Hitachi CDH-LE504KSMART22',
      precioStock: 79_799,
      descuento: 0.08,
      img: tv1,
      envioGratis: true,
      cuotas: 12,
      enStock: true,
      planCanje: false,
   },
   {
      id: nanoid(5),
      titulo: 'Calular Samsung Galaxy S20FE 128 GB AZUL',
      precioStock: 95_999,
      descuento: 0,
      img: cel1,
      envioGratis: true,
      cuotas: 6,
      enStock: true,
      planCanje: true,
   },
   {
      id: nanoid(5),
      titulo: 'Bordeadora Eléctrica Dibra B45002R',
      precioStock: 16_999,
      descuento: 0.23,
      img: bordeadora1,
      envioGratis: true,
      cuotas: 3,
      enStock: false,
      planCanje: false,
   },
   {
      id: nanoid(5),
      titulo: 'Heladera Cíclica Gafa HGF367AFP Plata 330 Lts',
      precioStock: 87_599,
      descuento: 0,
      img: heladera1,
      envioGratis: true,
      cuotas: 18,
      enStock: false,
      planCanje: false,
   },
   {
      id: nanoid(5),
      titulo: 'Batidora de Mesa Planetaria Smartlife SL-SB0037R',
      precioStock: 24_999,
      descuento: 0.2,
      img: batidora1,
      envioGratis: true,
      cuotas: 3,
      enStock: true,
      planCanje: false,
   },
   {
      id: nanoid(5),
      titulo: 'Lavavajillas Whirlpool Sense Inverte WSFO3T22 10 C',
      precioStock: 171_099,
      descuento: 0.33,
      img: lavavajillas1,
      envioGratis: true,
      cuotas: 6,
      enStock: false,
      planCanje: false,
   },
   {
      id: nanoid(5),
      titulo:
         'Notebook Iqual Nq3x Intel Core i3 10ma 8GB 1TB Full HD Windows 10',
      precioStock: 92_099,
      descuento: 0.15,
      img: notebook1,
      envioGratis: true,
      cuotas: 12,
      enStock: false,
      planCanje: false,
   },
   {
      id: nanoid(5),
      titulo:
         'Springwall Sommier y Colchón de Resortes 2 Plazas Springwall 140x190cm MCB 115',
      precioStock: 69_099,
      descuento: 0.28,
      img: cama1,
      envioGratis: true,
      cuotas: 12,
      enStock: false,
      planCanje: false,
   },
   {
      id: nanoid(5),
      titulo:
         'Sillón de 3 Cuerpos Esquinero Convertible American Wood Chenille Gris',
      precioStock: 92_488,
      descuento: 0.2,
      img: sillon1,
      envioGratis: true,
      cuotas: 18,
      enStock: true,
      planCanje: false,
   },
   {
      id: nanoid(5),
      titulo: 'Cocina Multigas Whirlpool WF160XB 60 cm Blanca',
      precioStock: 152_799,
      descuento: 0.35,
      img: cocina1,
      envioGratis: true,
      cuotas: 12,
      enStock: false,
      planCanje: false,
   },
];

export { slideImages, categoriesData, products };
